[package]
name = "moss-server"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
tracing = { workspace = true }
moss-lib = { path = "../moss-lib" }
