//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "function_conf")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub function_id: i32,
    pub name: String,
    pub value: String,
    pub conf_type: String,
    pub status: String,
    pub created_at: DateTimeUtc,
    pub deleted_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
