//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub uuid: String,
    pub username: String,
    pub nickname: String,
    #[sea_orm(unique)]
    pub email: String,
    pub avatar: String,
    pub phone: String,
    pub status: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::function_info::Entity")]
    FunctionInfo,
    #[sea_orm(has_many = "super::user_token::Entity")]
    UserToken,
}

impl Related<super::function_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FunctionInfo.def()
    }
}

impl Related<super::user_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserToken.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
