[package]
name = "moss-rpc"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
prost = "0.11.6"
tonic = "0.8.3"
tracing = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
tonic-build = "0.8.3"
