# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build
on:
  push:
    branches: [main]
    tags: ["v*"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "moss-wasm"
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add clippy
          rustup target add wasm32-unknown-unknown
          rustup target add wasm32-wasi
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: Run examples
        run: |
          cargo build -p rust-basic --target wasm32-wasi --release && cargo run --release rust-basic
          cargo build -p rust-fetch --target wasm32-wasi --release && cargo run --release rust-fetch
